// PTS Sales - หน้าเว็บ (GitHub Pages)
// ตั้งค่าลิงก์ API ที่ไฟล์ config.js
// ไฟล์นี้เป็นโค้ดสาธารณะ ห้ามใส่รหัสผ่าน คีย์ หรือข้อมูลลูกค้าใดๆ ลงในนี้

const state={user:null,master:[],statuses:[],priorities:[],categories:[],activityTypes:[],customers:[],users:[],mine:true,sla:{warn:7,overdue:15}};
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const date=v=>v?new Intl.DateTimeFormat('th-TH',{dateStyle:'medium'}).format(new Date(v)): '-';
const dt=v=>v?new Intl.DateTimeFormat('th-TH',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)): '-';
const statusClass=s=>'status-'+String(s).replace(/\s|\//g,'-');
const TOKEN_KEY='pts_token',NAME_KEY='pts_name';
const token=()=>{try{return localStorage.getItem(TOKEN_KEY)||''}catch(e){return ''}};
const setAuth=(t,n)=>{try{localStorage.setItem(TOKEN_KEY,t);localStorage.setItem(NAME_KEY,n)}catch(e){}};
const clearAuth=()=>{try{localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(NAME_KEY)}catch(e){}};
async function call(action,data){
  if(!window.API_URL)return{success:false,message:'ยังไม่ได้ตั้งค่า API_URL ในไฟล์ config.js'};
  try{
    const res=await fetch(window.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:action,data:data===undefined?null:data,token:token()})});
    const out=await res.json();
    if(out&&out.authError){clearAuth();loginScreen(out.message);return{success:false,message:out.message,handled:true}}
    return out;
  }catch(err){return{success:false,message:'เชื่อมต่อเซิร์ฟเวอร์ไม่ได้ ตรวจสอบอินเทอร์เน็ตแล้วลองใหม่'}}
}
function toast(message,ok=false){const x=$('#toast');x.textContent=message;x.className=`fixed right-4 top-4 z-50 rounded-xl px-4 py-3 text-sm shadow-lg ${ok?'bg-emerald-600 text-white':'bg-rose-600 text-white'}`;x.classList.remove('hidden');setTimeout(()=>x.classList.add('hidden'),3200)}
const nowLocal=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
const myName=()=>state.user?.Name||state.user?.Email||'';
function lockForm(e,on,text){const b=e.target.querySelector('button:not([type="button"])');if(!b)return;if(on){if(!b.dataset.label)b.dataset.label=b.textContent;b.textContent=text||'กำลังบันทึก…';b.disabled=true;b.classList.add('opacity-60')}else{b.textContent=b.dataset.label||b.textContent;b.disabled=false;b.classList.remove('opacity-60')}}
function loading(){ $('#app').innerHTML='<div class="p-8 text-center text-slate-500">กำลังโหลด…</div>'; }
function nav(active){$('#nav').innerHTML=[['dashboard','⌂','Dashboard'],['opportunities','▤','งานขาย'],['rfq','＋','RFQ'],['customers','♙','ลูกค้า']].map(n=>`<button onclick="route('${n[0]}')" class="min-w-16 text-xs ${active===n[0]?'font-bold text-teal-700':'text-slate-500'}"><span class="block text-xl">${n[1]}</span>${n[2]}</button>`).join('')}
let LOGIN_PW='';
function loginScreen(message,names){
  $('#nav').innerHTML='';
  $('#app').innerHTML=`<div class="flex min-h-screen items-center justify-center p-5"><form class="card w-full max-w-sm space-y-4" onsubmit="submitLogin(event)"><div class="text-center"><img src="logo-full.jpg" alt="PAKORN Technical Supply" class="mx-auto h-28 w-auto"><h1 class="mt-4 text-2xl font-bold text-teal-800">PTS Sales</h1><p class="mt-1 text-sm text-slate-500">ระบบติดตามงานขาย</p></div>${message?`<p class="rounded-lg bg-rose-50 p-2 text-center text-sm text-rose-700">${esc(message)}</p>`:''}${names?`<label><span class="label">คุณคือใคร *</span><select name="name" class="field" required><option value="">เลือกชื่อของคุณ</option>${names.map(n=>`<option>${esc(n)}</option>`).join('')}</select></label>`:`<label><span class="label">รหัสผ่านของทีม *</span><input name="password" type="password" class="field" required autocomplete="current-password" autofocus></label>`}<button class="btn btn-primary w-full">${names?'เข้าใช้งาน':'ถัดไป'}</button><p class="text-center text-xs text-slate-400">ระบบจะจำอุปกรณ์นี้ไว้ 30 วัน</p></form></div>`;
}
async function submitLogin(e){
  e.preventDefault();lockForm(e,true,'กำลังตรวจสอบ…');
  const f=Object.fromEntries(new FormData(e.target));
  if(f.password!==undefined)LOGIN_PW=f.password;
  const r=await call('login',{password:LOGIN_PW,name:f.name||''});
  if(!r.success){LOGIN_PW='';return loginScreen(r.message)}
  if(r.data&&r.data.needName)return loginScreen('',r.data.names);
  setAuth(r.data.token,r.data.name);LOGIN_PW='';start();
}
function logout(){if(!confirm('ออกจากระบบ?'))return;clearAuth();location.reload()}
async function start(){
  if(!token())return loginScreen();
  loading();
  const r=await call('getInitialData');
  if(!r.success){if(r.handled)return;$('#app').innerHTML=`<div class="m-5 card text-rose-700"><h1 class="font-bold">เข้าใช้งานไม่ได้</h1><p class="mt-2">${esc(r.message)}</p><button class="btn btn-secondary mt-3" onclick="logout()">ลองเข้าสู่ระบบใหม่</button></div>`;return}
  Object.assign(state,r.data);route('dashboard');
}
async function loadCustomers(){const r=await call('listCustomers','');if(r.success)state.customers=r.data}
async function loadUsers(){const r=await call('listUsers');if(r.success)state.users=r.data}
function route(name){if(name==='dashboard')dashboard();if(name==='opportunities')opportunities({owner:state.mine?myName():''});if(name==='rfq')rfqForm();if(name==='customers')customers()}
const pageTop=(title,sub='')=>`<header class="app-header flex items-center justify-between bg-teal-800 px-4 text-white"><div class="flex items-center gap-3"><img src="logo-mark.png" alt="" class="logo-tile h-9 w-9 shrink-0 object-contain"><div><h1 class="text-xl font-bold">${title}</h1>${sub?`<p class="text-xs text-teal-100">${sub}</p>`:''}</div></div><button onclick="logout()" class="text-right text-xs leading-tight">${esc(state.user?.Name||state.user?.Email||'')}<span class="block text-teal-200 underline">ออกจากระบบ</span></button></header>`;
function ageBadge(o){const n=o.Quote_Age_Days;if(n===null||n===undefined||n==='')return '';const w=state.sla?.warn??7,c=state.sla?.overdue??15;if(n<w)return '';return `<span class="badge ${n>=c?'bg-rose-100 text-rose-700':'bg-amber-100 text-amber-700'}">รอเสนอราคา ${n} วัน</span>`}
function cardOpp(o){return `<button onclick="detail('${esc(o.Opportunity_ID)}')" class="card w-full text-left"><div class="flex justify-between gap-2"><strong>${esc(o.Project_Name)}</strong><span class="flex shrink-0 flex-col items-end gap-1"><span class="badge ${statusClass(o.Status)}">${esc(o.Status)}</span>${ageBadge(o)}</span></div><div class="mt-1 text-sm text-slate-600">${esc(o.Customer?.Company_Name||'')} · ${esc(o.Opportunity_ID)}</div><div class="mt-2 text-xs text-slate-500">ผู้รับผิดชอบ ${esc(o.Owner)} · ติดตาม ${date(o.Next_Action_Date)} · ครบกำหนด ${date(o.Due_Date)}</div></button>`}
async function dashboard(){loading();nav('dashboard');const owner=state.mine?myName():'';const r=await call('dashboardData',owner);if(!r.success)return toast(r.message);const d=r.data;$('#app').innerHTML=pageTop('PTS Sales','ภาพรวมงานขาย')+`<section class="space-y-5 p-4"><div class="flex gap-2"><button onclick="setScope(true)" class="btn flex-1 ${state.mine?'btn-primary':'btn-secondary'}">งานของฉัน</button><button onclick="setScope(false)" class="btn flex-1 ${state.mine?'btn-secondary':'btn-primary'}">ทั้งทีม</button></div><div class="grid grid-cols-2 gap-3 sm:grid-cols-3">${Object.entries(d.counts).map(([k,v])=>`<button onclick="opportunities({status:'${esc(k)}',owner:'${esc(owner)}'})" class="card text-left"><div class="text-2xl font-bold text-teal-700">${v}</div><div class="mt-1 text-xs text-slate-600">${esc(k)}</div></button>`).join('')}</div>${quoteKpi(d.kpi)}${workList('เกินกำหนดเสนอราคา '+((d.kpi&&d.kpi.slaOverdueDays)||15)+' วัน',d.quoteOverdue||[],'ไม่มีงานเกินกำหนดเสนอราคา',true)}${workList('ใกล้ครบกำหนดเสนอราคา '+((d.kpi&&d.kpi.slaWarnDays)||7)+' วัน',d.quoteWarn||[],'ไม่มีงานใกล้ครบกำหนด','warn')}${workList('เลยวันติดตาม',d.followUpOverdue||[],'ไม่มีงานค้างติดตาม',true)}${workList('งานที่ต้องทำวันนี้',d.today,'ไม่มีงานติดตามวันนี้')}${workList('งานเกินกำหนดส่ง',d.overdue,'ไม่มีงานเกินกำหนด')}</section>`}
function quoteKpi(k){if(!k)return '';const rate=k.onTimeRate==null?'—':k.onTimeRate+'%';const avg=k.avgLeadDays==null?'—':k.avgLeadDays+' วัน';const tone=k.onTimeRate==null?'text-slate-400':k.onTimeRate>=80?'text-emerald-600':k.onTimeRate>=60?'text-amber-600':'text-rose-600';return `<section class="card"><h2 class="font-bold">KPI การเสนอราคา</h2><p class="mt-1 text-xs text-slate-500">นับจากวันที่ลูกค้าขอราคา ถึงวันที่ส่งใบเสนอราคา · เป้าหมายภายใน ${k.slaWarnDays} วัน</p><div class="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4"><div><div class="text-2xl font-bold ${tone}">${rate}</div><div class="text-xs text-slate-600">เสนอราคาทันเป้า</div></div><div><div class="text-2xl font-bold text-slate-700">${avg}</div><div class="text-xs text-slate-600">เฉลี่ยที่ใช้จริง</div></div><div><div class="text-2xl font-bold text-amber-600">${k.quoteWarn}</div><div class="text-xs text-slate-600">เกิน ${k.slaWarnDays} วัน</div></div><div><div class="text-2xl font-bold text-rose-600">${k.quoteOverdue}</div><div class="text-xs text-slate-600">เกิน ${k.slaOverdueDays} วัน</div></div></div><p class="mt-3 text-xs text-slate-400">${k.quotedCount?'คำนวณจากงานที่ส่งใบเสนอราคาแล้ว '+k.quotedCount+' งาน · ยังรอเสนอราคาอีก '+k.pendingQuote+' งาน':'ยังไม่มีงานที่บันทึกวันส่งใบเสนอราคา — ระบบจะเริ่มนับให้อัตโนมัติเมื่อเปลี่ยนสถานะเป็น “ส่งใบเสนอราคาแล้ว”'}</p></section>`}
function setScope(mine){state.mine=mine;dashboard()}
function workList(title,items,empty,tone){const warn=tone==='warn',danger=tone===true||tone==='danger';return `<section><h2 class="mb-2 flex items-center gap-2 font-bold ${items.length?(danger?'text-rose-600':warn?'text-amber-600':''):''}">${title}${items.length?`<span class="badge ${danger?'bg-rose-100 text-rose-700':warn?'bg-amber-100 text-amber-700':'bg-slate-200 text-slate-600'}">${items.length}</span>`:''}</h2><div class="space-y-2">${items.length?items.map(cardOpp).join(''):`<div class="card text-sm text-slate-500">${empty}</div>`}</div></section>`}
async function opportunities(filter={}){loading();nav('opportunities');const r=await call('listOpportunities',filter);if(!r.success)return toast(r.message);renderOppList(r.data,filter)}
function renderOppList(rows,filter){$('#app').innerHTML=pageTop('งานขาย',`${rows.length} รายการ`)+`<section class="space-y-3 p-4"><div class="flex gap-2"><input id="search" value="${esc(filter.query||'')}" class="field" placeholder="ค้นหา งาน / บริษัท / โทร / QT" onkeydown="if(event.key==='Enter'){event.preventDefault();searchOpp()}"><button class="btn btn-primary" onclick="searchOpp()">ค้นหา</button></div><div class="grid grid-cols-3 gap-2"><select id="fstatus" class="field text-xs"><option value="">ทุกสถานะ</option>${state.statuses.map(s=>`<option ${filter.status===s?'selected':''}>${esc(s)}</option>`).join('')}</select><select id="fowner" class="field text-xs"><option value="">ทุกผู้รับผิดชอบ</option>${owners().map(s=>`<option ${filter.owner===s?'selected':''}>${esc(s)}</option>`).join('')}</select><select id="fpriority" class="field text-xs"><option value="">ทุกความสำคัญ</option>${state.priorities.map(s=>`<option ${filter.priority===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="space-y-2">${rows.length?rows.map(cardOpp).join(''):'<div class="card text-center text-slate-500">ไม่พบงานขาย</div>'}</div></section>`}
function searchOpp(){opportunities({query:$('#search').value,status:$('#fstatus').value,owner:$('#fowner').value,priority:$('#fpriority').value})}
function owners(){return [...new Set(state.users.map(x=>x.Name||x.Email).filter(Boolean))]}
function customerOptions(selected=''){return `<option value="">เลือกลูกค้า</option>${state.customers.map(c=>`<option value="${esc(c.Customer_ID)}" ${selected===c.Customer_ID?'selected':''}>${esc(c.Company_Name)}${c.Contact_Name?' — '+esc(c.Contact_Name):''}</option>`).join('')}`}
function select(name,label,options,value='',required=false){return `<label><span class="label">${label}${required?' *':''}</span><select name="${name}" class="field" ${required?'required':''}>${options.map(x=>`<option value="${esc(x)}" ${x===value?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`}
function rfqForm(o={}){nav('rfq');const workTypes=state.master.filter(x=>x.Type==='Work_Type').map(x=>x.Name);$('#app').innerHTML=pageTop(o.Opportunity_ID?'แก้ไขงานขาย':'+ ขอใบเสนอราคา')+`<form class="space-y-4 p-4" onsubmit="saveOpp(event,'${esc(o.Opportunity_ID||'')}')"><div class="card space-y-3"><h2 class="font-bold">ข้อมูลหลัก</h2><label><span class="label">ลูกค้า *</span><select name="Customer_ID" class="field" required>${customerOptions(o.Customer_ID)}</select></label>${input('Project_Name','ชื่อโครงการ',o.Project_Name,'text',true)}${input('Site_Location','สถานที่หน้างาน',o.Site_Location)}${select('Work_Type','ประเภทงาน',[''].concat(workTypes),o.Work_Type)}<label><span class="label">รายละเอียด</span><textarea name="Description" class="field" rows="3">${esc(o.Description)}</textarea></label></div><div class="card grid grid-cols-1 gap-3 sm:grid-cols-2">${select('Priority','ความสำคัญ',state.priorities,o.Priority||'Normal')}${input('Due_Date','ครบกำหนด',''+(o.Due_Date||''),'date')}${select('Owner','ผู้รับผิดชอบ',[''].concat(owners()),o.Owner,true)}${input('Estimated_Value','มูลค่าคาดการณ์',o.Estimated_Value,'number')} ${input('Quotation_No','เลขที่ใบเสนอราคา',o.Quotation_No)}${input('Quotation_Amount','มูลค่าใบเสนอราคา',o.Quotation_Amount,'number')}</div><div class="card space-y-3"><h2 class="font-bold">ติดตามงาน</h2>${input('Next_Action','Next Action',o.Next_Action,'text',true)}${input('Next_Action_Date','วันที่ติดตาม',o.Next_Action_Date,'date',true)}<label><span class="label">หมายเหตุ</span><textarea name="Remark" class="field" rows="2">${esc(o.Remark)}</textarea></label></div><button class="btn btn-primary w-full">บันทึก</button></form>`}
async function saveOpp(e,id){e.preventDefault();lockForm(e,true);const raw=Object.fromEntries(new FormData(e.target));if(id)raw.Opportunity_ID=id;const r=await call('saveOpportunity',raw);if(!r.success){lockForm(e,false);return toast(r.message)}toast(r.message,true);detail(r.data.Opportunity_ID||id)}
async function detail(id){loading();nav('opportunities');const r=await call('getOpportunity',id);if(!r.success)return toast(r.message);const d=r.data,o=d.opportunity,c=d.customer;$('#app').innerHTML=pageTop(o.Opportunity_ID,'รายละเอียดงานขาย')+`<section class="space-y-4 p-4"><div class="card"><div class="flex justify-between gap-3"><div><h2 class="text-lg font-bold">${esc(o.Project_Name)}</h2><p class="text-sm text-slate-600">${esc(c.Company_Name)}</p></div><span class="badge ${statusClass(o.Status)}">${esc(o.Status)}</span></div><div class="mt-4 grid grid-cols-2 gap-2 text-sm"><p><b>ผู้ขอราคา:</b> ${esc(o.Requester_Name||c.Contact_Name||'-')}</p><p><b>แผนก:</b> ${esc(o.Requester_Department||c.Department||'-')}</p><p><b>โทร:</b> ${esc(o.Requester_Phone||c.Phone||'-')}</p><p><b>ผู้รับผิดชอบ:</b> ${esc(o.Owner)}</p><p><b>ครบกำหนด:</b> ${date(o.Due_Date)}</p><p><b>Next Action:</b> ${esc(o.Next_Action||'-')}</p></div><div class="mt-4 grid grid-cols-2 gap-2"><button class="btn btn-secondary" onclick="editOpp('${esc(o.Opportunity_ID)}')">แก้ไข</button><button class="btn btn-primary" onclick="statusForm('${esc(o.Opportunity_ID)}','${esc(o.Status)}')">เปลี่ยนสถานะ</button>${o.Status!==voidStatus()?`<button class="btn col-span-2 bg-rose-50 text-rose-700" onclick="voidForm('${esc(o.Opportunity_ID)}')">ยกเลิกงาน</button>`:''}</div></div><div class="card text-sm"><p><b>สถานที่:</b> ${esc(o.Site_Location||'-')}</p><p class="mt-2"><b>รายละเอียด:</b> ${esc(o.Description||'-')}</p><p class="mt-2"><b>ใบเสนอราคา:</b> ${esc(o.Quotation_No||'-')} / ${esc(o.Quotation_Amount||'-')}</p></div><div class="grid grid-cols-2 gap-2"><button class="btn btn-secondary" onclick="activityForm('${esc(o.Opportunity_ID)}')">+ Activity</button><button class="btn btn-secondary" onclick="uploadForm('${esc(o.Opportunity_ID)}')">แนบไฟล์</button></div>${timeline(d.activities)}${attachments(d.attachments)}</section>`}
async function editOpp(id){const r=await call('getOpportunity',id);if(r.success)rfqForm(r.data.opportunity);else toast(r.message)}
function timeline(items){return `<section><h2 class="mb-2 font-bold">Timeline</h2><div class="space-y-2">${items.length?items.map(a=>`<div class="card"><div class="flex justify-between gap-2"><b>${esc(a.Activity_Type)}</b><span class="text-xs text-slate-500">${dt(a.Activity_Date)}</span></div><p class="mt-1 text-sm">${esc(a.Description)}</p></div>`).join(''):'<div class="card text-sm text-slate-500">ยังไม่มีกิจกรรม</div>'}</div></section>`}
function attachments(items){return `<section><h2 class="mb-2 font-bold">ไฟล์แนบ</h2><div class="space-y-2">${items.length?items.map(a=>`<div class="card flex items-center gap-2 text-sm"><a target="_blank" rel="noopener" href="${esc(a.Drive_URL)}" class="flex min-w-0 flex-1 justify-between gap-2"><span class="truncate">${esc(a.File_Name)}</span><span class="shrink-0 text-slate-500">${esc(a.Category)} ↗</span></a><button title="ลบไฟล์" onclick="removeFile('${esc(a.Attachment_ID)}','${esc(a.Opportunity_ID)}')" class="shrink-0 px-2 text-rose-600">✕</button></div>`).join(''):'<div class="card text-sm text-slate-500">ยังไม่มีไฟล์แนบ</div>'}</div></section>`}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div id="modal" class="modal fixed inset-0 z-40 flex items-end justify-center p-3 sm:items-center"><div class="max-h-[92vh] w-full max-w-lg overflow-auto rounded-2xl bg-white p-5">${html}</div></div>`)}function closeModal(){$('#modal')?.remove()}
function statusForm(id,current){const reasons=state.master.filter(x=>x.Type==='Close_Reason').map(x=>x.Name);modal(`<form class="space-y-3" onsubmit="submitStatus(event,'${esc(id)}')"><div class="flex justify-between"><h2 class="text-lg font-bold">เปลี่ยนสถานะ</h2><button type="button" onclick="closeModal()">✕</button></div>${select('Status','สถานะ',state.statuses,current,true)}${input('Quotation_Amount','Winning Amount','', 'number')}<label><span class="label">เหตุผลปิดงาน</span><select name="Close_Reason" class="field"><option value="">เลือกเหตุผล</option>${reasons.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label><span class="label">หมายเหตุ</span><textarea name="Remark" class="field"></textarea></label><button class="btn btn-primary w-full">ยืนยัน</button></form>`)}
async function submitStatus(e,id){e.preventDefault();lockForm(e,true);const r=await call('changeStatus',Object.assign({Opportunity_ID:id},Object.fromEntries(new FormData(e.target))));if(!r.success){lockForm(e,false);return toast(r.message)}closeModal();toast(r.message,true);detail(id)}
function activityForm(id){modal(`<form class="space-y-3" onsubmit="submitActivity(event,'${esc(id)}')"><div class="flex justify-between"><h2 class="text-lg font-bold">เพิ่ม Activity</h2><button type="button" onclick="closeModal()">✕</button></div>${select('Activity_Type','ประเภท',state.activityTypes,'Note',true)}<label><span class="label">รายละเอียด *</span><textarea name="Description" required class="field" rows="3"></textarea></label>${input('Activity_Date','วันที่/เวลา',nowLocal(),'datetime-local')}${input('Next_Action','Next Action')}${input('Next_Action_Date','วันติดตาม','', 'date')}<div class="rounded-xl border border-dashed border-slate-300 p-3"><p class="label">แนบรูป/เอกสารไปพร้อมกัน (ไม่บังคับ)</p>${select('Category','ประเภทไฟล์',state.categories,'Survey')}<label class="mt-2 block"><span class="label">เลือกไฟล์ (ไฟล์ละไม่เกิน 10 MB)</span><input name="files" type="file" multiple class="field"></label><label class="mt-2 block"><span class="label">หรือถ่ายรูปหน้างาน</span><input name="photos" type="file" accept="image/*" capture="environment" multiple class="field"></label></div><button class="btn btn-primary w-full">บันทึก</button></form>`)}
async function submitActivity(e,id){
  e.preventDefault();
  const form=e.target;
  const picked=[...form.files.files,...form.photos.files];
  if(picked.length>10)return toast('แนบได้ครั้งละไม่เกิน 10 ไฟล์');
  if(picked.some(x=>x.size>10*1024*1024))return toast('มีไฟล์ขนาดเกิน 10 MB');
  lockForm(e,true);
  const raw=Object.fromEntries(new FormData(form));
  delete raw.files;delete raw.photos;delete raw.Category;
  const r=await call('addActivity',Object.assign({Opportunity_ID:id},raw));
  if(!r.success){lockForm(e,false);return toast(r.message)}
  if(picked.length){
    lockForm(e,true,'กำลังอัปโหลดไฟล์…');
    const up=await call('uploadFiles',{Opportunity_ID:id,Category:form.Category.value||'Photo',files:await readFiles(picked)});
    if(!up.success){closeModal();toast('บันทึกกิจกรรมแล้ว แต่แนบไฟล์ไม่สำเร็จ: '+up.message);return detail(id)}
  }
  closeModal();toast(r.message,true);detail(id);
}
const readFiles=list=>Promise.all(list.map(x=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({name:x.name,mimeType:x.type,base64:r.result});r.onerror=reject;r.readAsDataURL(x)})));
function uploadForm(id){modal(`<form class="space-y-3" onsubmit="submitFiles(event,'${esc(id)}')"><div class="flex justify-between"><h2 class="text-lg font-bold">แนบไฟล์</h2><button type="button" onclick="closeModal()">✕</button></div>${select('Category','ประเภทไฟล์',state.categories,'RFQ',true)}<label><span class="label">เลือกไฟล์ (ไฟล์ละไม่เกิน 10 MB)</span><input name="files" type="file" multiple class="field"></label><label><span class="label">หรือถ่ายรูปหน้างาน</span><input name="photos" type="file" accept="image/*" capture="environment" multiple class="field"></label><button class="btn btn-primary w-full">อัปโหลด</button></form>`)}
async function submitFiles(e,id){e.preventDefault();const f=[...e.target.files.files,...e.target.photos.files];if(!f.length)return toast('กรุณาเลือกไฟล์หรือถ่ายรูปอย่างน้อย 1 ไฟล์');if(f.length>10)return toast('อัปโหลดได้ครั้งละไม่เกิน 10 ไฟล์');if(f.some(x=>x.size>10*1024*1024))return toast('มีไฟล์ขนาดเกิน 10 MB');lockForm(e,true,'กำลังอัปโหลด…');const files=await readFiles(f);const r=await call('uploadFiles',{Opportunity_ID:id,Category:e.target.Category.value,files});if(!r.success){lockForm(e,false);return toast(r.message)}closeModal();toast(r.message,true);detail(id)}
async function customers(){loading();nav('customers');const r=await call('listCustomers','');if(!r.success)return toast(r.message);state.customers=r.data;$('#app').innerHTML=pageTop('ลูกค้า',`${r.data.length} รายการ`)+`<section class="space-y-3 p-4"><div class="flex justify-between"><button class="btn btn-primary" onclick="customerForm()">+ เพิ่มลูกค้า</button><input id="csearch" oninput="filterCustomers()" class="field w-48" placeholder="ค้นหาบริษัท"></div><div id="customer-list" class="space-y-2">${renderCustomers(r.data)}</div></section>`}
function renderCustomers(rows){return rows.length?rows.map(c=>`<button onclick="customerForm('${esc(c.Customer_ID)}')" class="card w-full text-left"><b>${esc(c.Company_Name)}</b><p class="mt-1 text-sm text-slate-600">${esc(c.Contact_Name||'-')} · ${esc(c.Phone||'-')}</p></button>`).join(''):'<div class="card text-center text-slate-500">ไม่พบลูกค้า</div>'}
function filterCustomers(){const q=$('#csearch').value.toLowerCase();$('#customer-list').innerHTML=renderCustomers(state.customers.filter(c=>[c.Company_Name,c.Contact_Name,c.Phone,c.Email].join(' ').toLowerCase().includes(q)))}
async function customerForm(id=''){let c={};if(id){const r=await call('getCustomer',id);if(!r.success)return toast(r.message);c=r.data||{}}modal(`<form class="space-y-3" onsubmit="saveCustomerForm(event,'${esc(id)}')"><div class="flex justify-between"><h2 class="text-lg font-bold">${id?'แก้ไขลูกค้า':'เพิ่มลูกค้า'}</h2><button type="button" onclick="closeModal()">✕</button></div>${input('Company_Name','บริษัท',c.Company_Name,'text',true)}${input('Contact_Name','ผู้ติดต่อ',c.Contact_Name)}${input('Department','แผนก',c.Department)}${input('Phone','เบอร์โทรศัพท์',c.Phone,'tel')}${input('Email','Email',c.Email,'email')}<label><span class="label">ที่อยู่</span><textarea name="Address" class="field">${esc(c.Address||'')}</textarea></label>${input('Map_URL','Google Maps URL',c.Map_URL,'url')}<label><span class="label">หมายเหตุ</span><textarea name="Remark" class="field">${esc(c.Remark||'')}</textarea></label><button class="btn btn-primary w-full">บันทึก</button></form>`)}
async function saveCustomerForm(e,id){e.preventDefault();lockForm(e,true);const x=Object.fromEntries(new FormData(e.target));if(id)x.Customer_ID=id;const r=await call('saveCustomer',x);if(!r.success){lockForm(e,false);return toast(r.message)}await loadCustomers();closeModal();toast(r.message,true);customers()}
const voidStatus=()=>state.voidStatus||'ยกเลิก';
function voidForm(id){modal(`<form class="space-y-3" onsubmit="submitVoid(event,'${esc(id)}')"><div class="flex justify-between"><h2 class="text-lg font-bold text-rose-700">ยกเลิกงาน</h2><button type="button" onclick="closeModal()">✕</button></div><p class="text-sm text-slate-600">งานจะถูกทำเครื่องหมายว่ายกเลิก ไม่ถูกลบออกจากระบบ และยังค้นหาย้อนหลังได้</p><label><span class="label">เหตุผลที่ยกเลิก *</span><textarea name="Reason" required class="field" rows="3"></textarea></label><button class="btn w-full bg-rose-600 text-white">ยืนยันยกเลิกงาน</button></form>`)}
async function submitVoid(e,id){e.preventDefault();lockForm(e,true,'กำลังยกเลิก…');const r=await call('voidOpportunity',Object.assign({Opportunity_ID:id},Object.fromEntries(new FormData(e.target))));if(!r.success){lockForm(e,false);return toast(r.message)}closeModal();toast(r.message,true);detail(id)}
async function removeFile(id,oppId){if(!confirm('ลบไฟล์นี้หรือไม่? ไฟล์จะถูกย้ายไปถังขยะใน Drive'))return;const r=await call('deleteAttachment',id);if(!r.success)return toast(r.message);toast(r.message,true);detail(oppId)}
start();
function input(name,label,value='',type='text',required=false){let v=value||'';if(type==='date')v=String(v).slice(0,10);if(type==='datetime-local')v=String(v).slice(0,16);return `<label><span class="label">${label}${required?' *':''}</span><input name="${name}" type="${type}" value="${esc(v)}" class="field" ${required?'required':''}></label>`}

